version: "3.8"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
  api:
    container_name: api
    image: api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8585:8585
    restart: always
    env_file:
      - .env
    environment:
      - MONGO_URI="mongodb://mongodb:27017/elsa"
      - REDIS_HOST=redis
      - REDIS_REPLICA_HOST=redis
      - POSTGRES_TYPE_SYNCHRONIZE=true
    depends_on:
      mongodb:
        condition: service_healthy
    links:
      - "postgresql"
      - "redis"
  redis:
    image: "redis:7.0.12-alpine"
    command: redis-server
    ports:
      - 6379:6379
    volumes:
      - ./cache:/data
    logging:
      options:
        max-size: 100m
  frontend:
    container_name: frontend
    image: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - 3000:4033
    depends_on:
      - api
    links:
      - api
    environment:
      - REACT_APP_SERVER_URL=http://api:8585
      - REACT_APP_BACKEND_URL_BASE=http://api:9000
      - REACT_APP_WS_URL_BASE=ws://api:9001
      - REACT_APP_PUBLIC_URL=http://api:3000
    restart: always
